let exec = async () => {
    AddTextEntry('er34', 'Nissan ER34 Skyline');
    AddTextEntry('650slw', 'McLaren 650S Coupe Liberty Walk');
    AddTextEntry('golfp', 'Golf MK7 Pandem');
    AddTextEntry('c63', 'Mercedes-AMG C63');
    AddTextEntry('m4', 'BMW M4');
    AddTextEntry('rudiharley', 'Rudi Harley');
    AddTextEntry('zx10', 'Kawasaki Ninja ZX-10R');
    AddTextEntry('300zw', 'Nissan Fairlady Z 300ZW');
    AddTextEntry('bluecunt', 'Blue Cunt');
    AddTextEntry('filthynsx', 'Acura NSX');
    AddTextEntry('Filthy', 'Acura NSX');
    AddTextEntry('m5e60', 'BMW M5 (E60)');
    AddTextEntry('500gtrlam', 'Lamborghini Diablo GTR');
    AddTextEntry('wraith', 'Rolls-Royce Wraith');
    AddTextEntry('evo9', 'Mitsubishi Lancer Evo9 Drift');
    AddTextEntry('fc3s', 'Mazda FC RX-7 89');
    AddTextEntry('m235', 'BMW M235i');
    AddTextEntry('m3e46', 'BMW M3 E46');
    AddTextEntry('MBW124', 'Mercedes Benz MB W124 E-Class');
    AddTextEntry('esv', 'Cadillac Escalade ESV');
    AddTextEntry('nis13', 'Nissan Silvia S13');
    AddTextEntry('s13', 'Nissan Silvia S13');
    AddTextEntry('lwlp670', 'Lamborghini Murcielago LP670');
    AddTextEntry('DC5', 'Honda Integra Type R DC5');
    AddTextEntry('granlb', 'Maserati GT Liberty Walk');
    AddTextEntry('eclipse', 'Mitsubishi Eclipse');
    AddTextEntry('r35', 'Nissan GT-R R35');
    AddTextEntry('gtr', 'Nissan GT-R R35 Rocket Bunny');
    AddTextEntry('tempesta2', 'Lamborghini Gallardo');
    AddTextEntry('por930', 'Porsche 911 Turbo (930)');
    AddTextEntry('911930', 'Porsche 911 Turbo (930)');
    AddTextEntry('na1', 'Honda NSX NA1');
    AddTextEntry('gtrc', 'Mercedes-AMG C GTR');
    AddTextEntry('raid', 'Dodge Challanger LIFTED');
    AddTextEntry('cp9a', 'Mitsubishi Lancer Evo9');
    AddTextEntry('e36prb', 'BMW M3 E36 Pandem');
    AddTextEntry('PRB', 'BMW M3 E36 Pandem');
    AddTextEntry('mig', 'Ferrari Enzo MIG');
    AddTextEntry('migS', 'Ferrari Enzo MIG');
    AddTextEntry('z32', 'Nissan 300ZX Z32');
    AddTextEntry('300ZX', 'Nissan 300ZX Z32');
    AddTextEntry('gt2rwb', 'Porsche 993 GT2 RWB');
    AddTextEntry('69charger', 'Dodge Charger `69');
    AddTextEntry('C7', 'Chevy Corvette C7');
    AddTextEntry('na6', 'Mazda MX5');
    AddTextEntry('r1', 'Yamaha YZF-R1');
    AddTextEntry('audirs6tk', 'Audi RS6');
    AddTextEntry('rs6', 'Audi RS6');
    AddTextEntry('mustang19', 'Ford Mustang GT');
    AddTextEntry('MUSTGT19', 'Ford Mustang GT');
    AddTextEntry('rcf', 'Lexus RC F');
    AddTextEntry('gt63', 'Mercedes-AMG GT 63');
    AddTextEntry('s14boss', 'Nissan Silvia S14');
    AddTextEntry('FK8', 'Honda Civic Type R');
    AddTextEntry('exor', 'Hennessey Exorcist Camaro');
    AddTextEntry('focusrs', 'Ford Focus RS');
    AddTextEntry('lp670', 'Lamborghini Murcielago');
    AddTextEntry('srt8b', 'Jeep Grand Cherokee SRT8');
    AddTextEntry('fnfrx7', 'Mazda RX7');
    AddTextEntry('gt3rs', 'Porsche 911 GT3');
    AddTextEntry('f150', 'Ford F-150 Raptor');
    AddTextEntry('panamera17turbo', 'Porsche Panamera Turbo');
    AddTextEntry('PANAMERA17T', 'Porsche Panamera Turbo');
    AddTextEntry('s15rb', 'Nissan Silvia S15 Rocket Bunny');
    AddTextEntry('z2879', 'Chevrolet Camaro Z28');
    AddTextEntry('contss18', 'Bentley Continental GT');
    AddTextEntry('bdragon', 'Bentley Continental WB Dragon');
    AddTextEntry('p1', 'McLaren P1');
    AddTextEntry('laferrari17', 'Ferrari LaFerrari');
    AddTextEntry('918', 'Porsche 918 Spyder');
    AddTextEntry('918SPYDER', 'Porsche 918 Spyder');
    AddTextEntry('zondar', 'Pagani Zonda R');
    AddTextEntry('regera', 'Koenigsegg Regera');

    AddTextEntry('x6m', 'BMW X6 M');
    AddTextEntry('avz', 'Aston Martin Vanquish Zagato');
    AddTextEntry('bmci', 'BMW M5');
    AddTextEntry('M5', 'BMW M5');
    AddTextEntry('crawler', 'Crawler RockHammer');
    AddTextEntry('brabus700', 'Mercedes-Benz G 63 Brabus');
    AddTextEntry('bisonbutch', 'Bison Custom');
    AddTextEntry('cone', 'Royale Limousine');
    AddTextEntry('gmt900escalade', 'Cadillac Escalade GMT900');
    AddTextEntry('GMT900ESCAL', 'Cadillac Escalade GMT900');
    AddTextEntry('caprice13', 'Chevrolet Caprice');
    AddTextEntry('camaross', 'Chevrolet Camaro SS');
    AddTextEntry('corvetteZR1', 'Chevrolet Corvette ZR1');
    AddTextEntry('tampa3', 'Drift Tampa Custom');
    AddTextEntry('gt2017', 'Ford GT 2017');
    AddTextEntry('GT 2017', 'Ford GT 2017');
    AddTextEntry('gtcl', 'Ferrari GTC4Lusso');
    AddTextEntry('GTC4LUSSO', 'Ferrari GTC4Lusso');
    AddTextEntry('599gtox', 'Ferrari 599 GTO');
    AddTextEntry('fmgt', 'Ford Mustang GT');
    AddTextEntry('MUSTANG GT', 'Ford Mustang GT');
    AddTextEntry('gmcs', 'GMC Sierra');
    AddTextEntry('SIERRA 1500', 'GMC Sierra');
    AddTextEntry('gmcyd', 'GMC Yukon');
    AddTextEntry('dcd', 'Dodge Charger DEMON');
    AddTextEntry('gclas9', 'Mercedes-Benz G 500');
    AddTextEntry('G-CLASS 201', 'Mercedes-Benz G 500');
    AddTextEntry('s500w222', 'Mercedes-Benz S500');
    AddTextEntry('mers63c', 'Mercedes S63');
    AddTextEntry('S63C', 'Mercedes S63');
    AddTextEntry('tulenis', 'Nissan Patrol Nismo');
    AddTextEntry('xc60', 'Nissan Patrol Nismo');
    AddTextEntry('patrolsafari', 'Nissan Patrol Safari');
    AddTextEntry('patrolsafar', 'Nissan Patrol Safari');
    AddTextEntry('911rwb', 'Porche 911 RWB');
    AddTextEntry('techart17', 'Porche Carrera GT Techart');
    AddTextEntry('velar', 'Range Rover Velar');
    AddTextEntry('VELAR2018', 'Range Rover Velar');
    AddTextEntry('rculi', 'Rolls Royce Cullinan');
    AddTextEntry('CULLINAN 20', 'Rolls Royce Cullinan');
    AddTextEntry('hilux1', 'Toyota Hilux');
    AddTextEntry('HILUX', 'Toyota Hilux');

    AddTextEntry('polschafter3', 'UM Schafter');
    AddTextEntry('police2', 'Buffalo Cruiser');
    AddTextEntry('POL3', 'Ford Cruiser');
    AddTextEntry('POL5', 'Ford Explorer');
    AddTextEntry('POL6', 'Ford Explorer 2');
    AddTextEntry('POL9', 'Ford Raptor');
    AddTextEntry('POL10', 'Chevrolet Suburban');
    AddTextEntry('POL8', 'BMW F 900');
    AddTextEntry('POL2', 'Ford CVPI');

    AddTextEntry('BUGATTI', 'Bugatti Veyron');
    AddTextEntry('FD', 'Mazda RX-7');
    AddTextEntry('lp770', 'Lamborghini Centenario');
    AddTextEntry('CENTENARIO', 'Lamborghini Centenario');
    AddTextEntry('yFiat595ssA', 'Fiat Abarth 595');
    AddTextEntry('elcamino70', 'Chevrolet El Camino');
}
exec();